"""add sms model

Revision ID: 03efaee5723b
Revises: e0f528e68aa9
Create Date: 2026-02-27 18:49:32.125994

"""

from collections.abc import Sequence

# revision identifiers, used by Alembic.
revision: str = "03efaee5723b"  # pragma: allowlist secret
down_revision: str | Sequence[str] | None = "e0f528e68aa9"  # pragma: allowlist secret
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
