"""Add OIDCClient

Revision ID: 0ae45168ff18
Revises: 4bafd51bb520
Create Date: 2026-03-03 01:31:34.831455

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0ae45168ff18'
down_revision: Union[str, Sequence[str], None] = '4bafd51bb520'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('oidc_clients',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('client_id', sa.String(length=255), nullable=False),
    sa.Column('client_secret', sa.String(length=255), nullable=True),
    sa.Column('client_name', sa.String(length=255), nullable=True),
    sa.Column('redirect_uris', sa.JSON(), nullable=True),
    sa.Column('response_types', sa.JSON(), nullable=True),
    sa.Column('grant_types', sa.JSON(), nullable=True),
    sa.Column('token_endpoint_auth_method', sa.String(length=50), nullable=True),
    sa.Column('jwks_uri', sa.String(length=500), nullable=True),
    sa.Column('subject_type', sa.String(length=50), nullable=False),
    sa.Column('sector_identifier_uri', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_oidc_clients_client_id'), 'oidc_clients', ['client_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_oidc_clients_client_id'), table_name='oidc_clients')
    op.drop_table('oidc_clients')
    # ### end Alembic commands ###
