"""change avatar_url string to text

Revision ID: 0ebc1d2aa8d5
Revises: c9d3e5f7a1b2
Create Date: 2026-03-07 00:21:30.106401

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0ebc1d2aa8d5'
down_revision: Union[str, Sequence[str], None] = 'c9d3e5f7a1b2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('oidc_clients', sa.Column('tenant_id', sa.UUID(), nullable=True))
    op.create_index(op.f('ix_oidc_clients_tenant_id'), 'oidc_clients', ['tenant_id'], unique=False)
    op.create_foreign_key(None, 'oidc_clients', 'tenants', ['tenant_id'], ['id'], ondelete='SET NULL')
    op.add_column('tenant_sms_configs', sa.Column('account_sid', sa.String(), nullable=True))
    op.alter_column('users', 'avatar_url',
               existing_type=sa.VARCHAR(length=500),
               type_=sa.Text(),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'avatar_url',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=500),
               existing_nullable=True)
    op.drop_column('tenant_sms_configs', 'account_sid')
    op.drop_constraint(None, 'oidc_clients', type_='foreignkey')
    op.drop_index(op.f('ix_oidc_clients_tenant_id'), table_name='oidc_clients')
    op.drop_column('oidc_clients', 'tenant_id')
    # ### end Alembic commands ###
