"""add mfa related column

Revision ID: 4bafd51bb520
Revises: a48f25e886fa
Create Date: 2026-02-28 01:47:18.792618

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4bafd51bb520'
down_revision: Union[str, Sequence[str], None] = 'a48f25e886fa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('mfa_enabled', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    op.add_column('users', sa.Column('mfa_secret', sa.String(length=500), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'mfa_secret')
    op.drop_column('users', 'mfa_enabled')
    # ### end Alembic commands ###
