"""added tenant description in tentorm

Revision ID: 7331f6b95d19
Revises: 3bfcc32c83dd
Create Date: 2026-02-17 11:33:33.297507

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "7331f6b95d19"  # pragma: allowlist secret
down_revision: str | Sequence[str] | None = "3bfcc32c83dd"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "tenants",
        sa.Column("description", sa.String(length=500), nullable=False, server_default=""),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("tenants", "description")
    # ### end Alembic commands ###
