"""add level to roles

Revision ID: eb4efa51615c
Revises: 6614a77fe7c5
Create Date: 2026-02-17 14:12:19.702883

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "eb4efa51615c"  # pragma: allowlist secret
down_revision: str | Sequence[str] | None = "6614a77fe7c5"  # pragma: allowlist secret
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("roles", sa.Column("level", sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("roles", "level")
    # ### end Alembic commands ###
